console.log('Hello Winc Academy');
let name = 'Andrea';
console.log(name);
var a = 4;
var b = 4;
console.log(a+b);
console.log(a*b);
console.log(a-b);
console.log(a/b);
console.log(a%b);
var age = '26';
console.log(typeof age);